services:
  mongodb:
    build:
      context: ./mongo   # use custom Dockerfile
    image: my-mongo-rs:8
    container_name: homeserver-mongodb
    restart: unless-stopped
    command: mongod --noauth --replSet rs0
    environment:
      MONGO_INITDB_DATABASE: home
      # Use "localhost:27017" if connecting from host
      # Use "homeserver-mongodb:27017" if connecting from another container
      MONGO_RS_HOST: "localhost:27017"
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
  mongodb_config:
